<?php

namespace Curso\PruebaDoctrineBundle\Entity;

use Doctrine\ORM\EntityRepository;

/**
 * CursoCategoriaRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class CursoCategoriaRepository extends EntityRepository
{
}