parameters:
#    curso_formulario.example.class: Curso\FormularioBundle\Example

services:
#    curso_formulario.example:
#        class: %curso_formulario.example.class%
#        arguments: [@service_id, "plain_value", %parameter%]
